#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CompleteApp.Resource", IsApplication=true)]

namespace CompleteApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LoginScreen.Resource.Drawable.alert = global::CompleteApp.Resource.Drawable.alert;
			global::LoginScreen.Resource.Drawable.arrow = global::CompleteApp.Resource.Drawable.arrow;
			global::LoginScreen.Resource.Drawable.bg_login = global::CompleteApp.Resource.Drawable.bg_login;
			global::LoginScreen.Resource.Drawable.button_login = global::CompleteApp.Resource.Drawable.button_login;
			global::LoginScreen.Resource.Drawable.button_login_pressed = global::CompleteApp.Resource.Drawable.button_login_pressed;
			global::LoginScreen.Resource.Drawable.button_login_selector = global::CompleteApp.Resource.Drawable.button_login_selector;
			global::LoginScreen.Resource.Drawable.button_register = global::CompleteApp.Resource.Drawable.button_register;
			global::LoginScreen.Resource.Drawable.button_register_pressed = global::CompleteApp.Resource.Drawable.button_register_pressed;
			global::LoginScreen.Resource.Drawable.button_register_selector = global::CompleteApp.Resource.Drawable.button_register_selector;
			global::LoginScreen.Resource.Drawable.button_reset = global::CompleteApp.Resource.Drawable.button_reset;
			global::LoginScreen.Resource.Drawable.button_reset_pressed = global::CompleteApp.Resource.Drawable.button_reset_pressed;
			global::LoginScreen.Resource.Drawable.button_reset_selector = global::CompleteApp.Resource.Drawable.button_reset_selector;
			global::LoginScreen.Resource.Drawable.divider_bottom = global::CompleteApp.Resource.Drawable.divider_bottom;
			global::LoginScreen.Resource.Drawable.divider_top = global::CompleteApp.Resource.Drawable.divider_top;
			global::LoginScreen.Resource.Drawable.edittext_bg_selector = global::CompleteApp.Resource.Drawable.edittext_bg_selector;
			global::LoginScreen.Resource.Drawable.edittext_textcolor_selector = global::CompleteApp.Resource.Drawable.edittext_textcolor_selector;
			global::LoginScreen.Resource.Drawable.Icon = global::CompleteApp.Resource.Drawable.Icon;
			global::LoginScreen.Resource.Drawable.image_password = global::CompleteApp.Resource.Drawable.image_password;
			global::LoginScreen.Resource.Drawable.image_password_active = global::CompleteApp.Resource.Drawable.image_password_active;
			global::LoginScreen.Resource.Drawable.image_username = global::CompleteApp.Resource.Drawable.image_username;
			global::LoginScreen.Resource.Drawable.image_username_active = global::CompleteApp.Resource.Drawable.image_username_active;
			global::LoginScreen.Resource.Drawable.password_right_selector = global::CompleteApp.Resource.Drawable.password_right_selector;
			global::LoginScreen.Resource.Drawable.textfield = global::CompleteApp.Resource.Drawable.textfield;
			global::LoginScreen.Resource.Drawable.textfield_active = global::CompleteApp.Resource.Drawable.textfield_active;
			global::LoginScreen.Resource.Drawable.username_right_selector = global::CompleteApp.Resource.Drawable.username_right_selector;
			global::LoginScreen.Resource.Id.bottomSpace = global::CompleteApp.Resource.Id.bottomSpace;
			global::LoginScreen.Resource.Id.confirmPasswordEdit = global::CompleteApp.Resource.Id.confirmPasswordEdit;
			global::LoginScreen.Resource.Id.emailEdit = global::CompleteApp.Resource.Id.emailEdit;
			global::LoginScreen.Resource.Id.errorLayout = global::CompleteApp.Resource.Id.errorLayout;
			global::LoginScreen.Resource.Id.errorMessage = global::CompleteApp.Resource.Id.errorMessage;
			global::LoginScreen.Resource.Id.fake = global::CompleteApp.Resource.Id.fake;
			global::LoginScreen.Resource.Id.forgotLayout = global::CompleteApp.Resource.Id.forgotLayout;
			global::LoginScreen.Resource.Id.forgotText = global::CompleteApp.Resource.Id.forgotText;
			global::LoginScreen.Resource.Id.loginButton = global::CompleteApp.Resource.Id.loginButton;
			global::LoginScreen.Resource.Id.loginEdit = global::CompleteApp.Resource.Id.loginEdit;
			global::LoginScreen.Resource.Id.loginLayout = global::CompleteApp.Resource.Id.loginLayout;
			global::LoginScreen.Resource.Id.loginText = global::CompleteApp.Resource.Id.loginText;
			global::LoginScreen.Resource.Id.noAccountImage = global::CompleteApp.Resource.Id.noAccountImage;
			global::LoginScreen.Resource.Id.noAccountSection = global::CompleteApp.Resource.Id.noAccountSection;
			global::LoginScreen.Resource.Id.noAccountText = global::CompleteApp.Resource.Id.noAccountText;
			global::LoginScreen.Resource.Id.passwordEdit = global::CompleteApp.Resource.Id.passwordEdit;
			global::LoginScreen.Resource.Id.registerButton = global::CompleteApp.Resource.Id.registerButton;
			global::LoginScreen.Resource.Id.registerText = global::CompleteApp.Resource.Id.registerText;
			global::LoginScreen.Resource.Id.resetButton = global::CompleteApp.Resource.Id.resetButton;
			global::LoginScreen.Resource.Id.resetText = global::CompleteApp.Resource.Id.resetText;
			global::LoginScreen.Resource.Id.rootLayout = global::CompleteApp.Resource.Id.rootLayout;
			global::LoginScreen.Resource.Id.titleLayout = global::CompleteApp.Resource.Id.titleLayout;
			global::LoginScreen.Resource.Layout.a_login = global::CompleteApp.Resource.Layout.a_login;
			global::LoginScreen.Resource.Layout.a_register = global::CompleteApp.Resource.Layout.a_register;
			global::LoginScreen.Resource.Layout.a_reset = global::CompleteApp.Resource.Layout.a_reset;
			global::LoginScreen.Resource.Layout.a_validationerror = global::CompleteApp.Resource.Layout.a_validationerror;
			global::LoginScreen.Resource.String.library_name = global::CompleteApp.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_login = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_login_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_login_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_register = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_register_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_register_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_reset = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_reset_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_reset_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int divider_bottom = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int divider_top = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int edittext_bg_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int edittext_textcolor_selector = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int image_password = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int image_password_active = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int image_username = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int image_username_active = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int password_right_selector = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int textfield = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int textfield_active = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int username_right_selector = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050025
			public const int addButton = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int addIngredient = 2131034151;
			
			// aapt resource value: 0x7f05000d
			public const int bottomSpace = 2131034125;
			
			// aapt resource value: 0x7f05001e
			public const int button1 = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int button2 = 2131034140;
			
			// aapt resource value: 0x7f05002b
			public const int button3 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int button4 = 2131034156;
			
			// aapt resource value: 0x7f050011
			public const int confirmPasswordEdit = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int editText1 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int editText2 = 2131034138;
			
			// aapt resource value: 0x7f050010
			public const int emailEdit = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int errorLayout = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int errorMessage = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int fake = 2131034120;
			
			// aapt resource value: 0x7f05001f
			public const int foodText = 2131034143;
			
			// aapt resource value: 0x7f050006
			public const int forgotLayout = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int forgotText = 2131034119;
			
			// aapt resource value: 0x7f050029
			public const int imageButton1 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int linearLayout2 = 2131034154;
			
			// aapt resource value: 0x7f050005
			public const int loginButton = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int loginEdit = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int loginLayout = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int loginText = 2131034114;
			
			// aapt resource value: 0x7f050026
			public const int myListView = 2131034150;
			
			// aapt resource value: 0x7f05000a
			public const int noAccountImage = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int noAccountSection = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int noAccountText = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int passwordEdit = 2131034116;
			
			// aapt resource value: 0x7f050020
			public const int quantity = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int radioButton1 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int radioButton2 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int radioButton3 = 2131034148;
			
			// aapt resource value: 0x7f050021
			public const int radioGroup1 = 2131034145;
			
			// aapt resource value: 0x7f05000c
			public const int registerButton = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int registerText = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int resetButton = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int resetText = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int rootLayout = 2131034112;
			
			// aapt resource value: 0x7f05002f
			public const int signInWithEmailButton = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int signInWithFacebookButton = 2131034160;
			
			// aapt resource value: 0x7f050028
			public const int space1 = 2131034152;
			
			// aapt resource value: 0x7f05002e
			public const int space2 = 2131034158;
			
			// aapt resource value: 0x7f050018
			public const int space3 = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int space4 = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int space5 = 2131034134;
			
			// aapt resource value: 0x7f05001d
			public const int space6 = 2131034141;
			
			// aapt resource value: 0x7f050017
			public const int textView1 = 2131034135;
			
			// aapt resource value: 0x7f05002d
			public const int textView2 = 2131034157;
			
			// aapt resource value: 0x7f05000e
			public const int titleLayout = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int a_login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int a_register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int a_reset = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int a_validationerror = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int facebook_login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hub = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Ingredient_View_AddIngredient = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Ingredient_View_Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Ingredient_View_update_amount = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int login = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
